version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fabrika
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/fabrika

volumes:
  db_data:
